
server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: never
    include-exception: true

# POSTGRESQL SETTINGS
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/logistic_db
    username: logistic_user
    password: logistic_pass
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
    properties:
      '[hibernate.format_sql]': true

logistic:
  app:
    jwtSecret: logistic@System@3414
    jwtExpirationMs: 86400000

#image
servlet:
  multipart:
    max-file-size: 5MB
    max-request-size: 5MB

logging:
  file:
    name: logs/logistic.log
  pattern:
    file: "%d %-5level [%thread] %logger:%msg%n"
  level:
    '[org.springframework.web]': WARN
    '[org.hibernate]': INFO
    '[logistic]': DEBUG

management: #actuator
  endpoints:
    web:
      exposure:
        include: '*'
  info:
    env:
      enabled: true
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true



info:
  application:
    name: 'Logistic Management Application'
    description: 'This is Logistic Backend App developed by Feridun OZCELIK'
    version: '@project.version@'

